export const universities = [
  "University of Chester",
  "University of Lincoln",
  "University of Portsmouth",
  "Birmingham City University",
  "University of Huddersfield",
  "University of Bolton",
  "Glasgow Caledonian University (GCU)",
  "University of Northampton",
  "Northumbria University",
  "Ulster University",
  "University of the West of Scotland",
  "University of Greenwich",
  "Kingston University",
  "University of Roehampton",
  "University of Hertfordshire",
  "Ravensbourne University London",
  "University of South Wales",
  "Coventry University",
  "De Montfort University",
  "Sheffield Hallam University",
  "Bangor University",
  "University of Bradford"
];
